# Generated by Django 3.1.6 on 2021-07-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemModel',
        ),
    ]
